name: Deploy Frontend to Railway

on:
  push:
    branches:
      - main
    paths:
      # Trigger only on changes to frontend files
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'railway.json'
      - '.github/workflows/deploy-frontend-railway.yml'
  workflow_dispatch:

# Prevent multiple concurrent deployments for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend-to-railway:
    name: Deploy Frontend to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Using npm as per prebuild-check.yml

      - name: Install dependencies
        run: npm ci

      - name: Run a local build test
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://placeholder.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'placeholder' }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Deploying frontend service to Railway..."
          # The `railway up` command will use the railway.json file in the root
          # to build and deploy the service.
          railway up --detach