runtime: python311

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app

env_variables:
  # These will be replaced by GitHub Actions during deployment
  MONGODB_URI: ${MONGODB_URI}
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  JWT_SECRET: ${JWT_SECRET}
  FRONTEND_URL: https://eka-ai-c9d24.web.app

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
